[build]
  publish = "."  # Публикация из корня проекта
  command = ""  # Если проект не требует сборки (например, чистые статические файлы)

[[plugins]]
  package = "@netlify/plugin-image-optimizer"
  disabled = true  # Отключить сжатие изображений
